Use a non-broken openjdk image
Upgrading the JDK fixes the issue seen on the Nationwide server where
TLS connections failed with:

fapi-conformance-suite    2018-01-11T11:32:12.448497838Z    Caused by:
java.security.InvalidAlgorithmParameterException: DH key size must be
multiple of 64, and can only range from 512 to 2048 (inclusive). The
specific key size 4096 is not supported