CallClientConfigurationEndpointAllowingTLSFailure: Allow socket exception
The radiam mock bank sometimes fails with:

I/O error on GET request for
"https://matls-auth.mockbank.poc.raidiam.io/reg/Zij8Xa3wwl9-Ot8Mbgj3f":
Broken pipe (Write failed); nested exception is
java.net.SocketException: Broken pipe (Write failed)

instead of the expected SSLException. This particularly happens when
our server is running slow (i.e. in our CI where there are lots of
jobs running in parallel).

Since it's almost impossible to fake this test (we require the next
call milliseconds later to be successful) it seems okay to allow the
extra error as a pass.